export enum ErrorCode {
  DDB_RESOURCE_NOT_FOUND = 'DDB_RESOURCE_NOT_FOUND',
  DDB_THROUGHPUT_EXCEEDED = 'DDB_THROUGHPUT_EXCEEDED',
  DDB_VALIDATION_ERROR = 'DDB_VALIDATION_ERROR',
  DDB_INTERNAL_SERVER_ERROR = 'DDB_INTERNAL_SERVER_ERROR',
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  TASK_CONVERSION_ERROR = 'TASK_CONVERSION_ERROR',
  TASK_UNKNOWN_ERROR = 'TASK_UNKNOWN_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_REQUEST = 'INVALID_REQUEST',
}
